### POST - CRIAR CARGO
POST http://localhost:9000/cargos
Content-Type: application/json

{
  "nome": "Dev"
}

### GET - LISTAR CARGOS
GET http://localhost:9000/cargos

### GET - BUSCAR CARGO POR ID
GET http://localhost:9000/cargos/5

### PATCH - ATUALIZAR CARGO
PATCH http://localhost:9000/cargos/5
Content-Type: application/json

{
  "nome": "Desenvolvedor"
}

### DELETE - DELETAR CARGO
DELETE http://localhost:9000/cargos/{id}