### POST - CRIAR usuarios
POST http://localhost:9000/usuarios
Content-Type: application/json

{
  "nome": "Rodolfo Ferreira",
  "email": "rodolfo@gmail.com",
  "senha": "1234",
  "cargo": "Musico"
}

### GET - LISTAR usuarios
GET http://localhost:9000/usuarios

### GET - BUSCAR usuarios POR ID
GET http://localhost:9000/usuarios/dde2ac0b-d928-45e7-856d-7ac9ad75f055

### PATCH - ATUALIZAR usuarios
PATCH http://localhost:9000/usuarios/5
Content-Type: application/json

{
  "nome": "Desenvolvedor"
}

### DELETE - DELETAR usuarios
DELETE http://localhost:9000/usuarios/{id}