### POST - CRIAR usuarios
POST http://localhost:9000/usuarios
Content-Type: application/json

{
  "nome": "Paulo",
  "email": "paulo1@gmail.com",
  "senha": "12345",
  "cargo": "Ministro",
  "naipe": "Tenor"
}

### GET - LISTAR usuarios
GET http://localhost:9000/usuarios

### GET - LISTAR usuarios Cargos
GET http://localhost:9000/usuarios/cargo/ministros

### GET - LISTAR usuarios Naipes
GET http://localhost:9000/usuarios/naipes/Tenor

### GET - BUSCAR usuarios POR ID
GET http://localhost:9000/usuarios/1c12ffce-3752-4322-a193-f15dbf8a13c1

### PATCH - ATUALIZAR usuarios
PATCH http://localhost:9000/usuarios/1c12ffce-3752-4322-a193-f15dbf8a13c1
Content-Type: application/json

{
  "nome": "Isaac",
  "email": "Isaac@gmail.com",
  "senha": "12345",
  "cargo": "Musico",
  "naipe": "Guitarra"
}

### DELETE - DELETAR usuarios
DELETE http://localhost:9000/usuarios/{id}